server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/course/**

        - id: student-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/student/**
        - id: note-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/grade/**
