server:
  port: 8082

spring:
  application:
    name: student-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: studentDB

logging:
  level:
    root: INFO
    com.studentmanagement.course_service: DEBUG